name: AWS Lambda CICD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          S3_BUCKET: 'deliverynow-bucket'
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install

      - name: Push bucket
        run: |
          aws s3 cp target/HelloWorld-1.0.jar s3://$S3_BUCKET/
#        run: aws lambda update-function-code --function-name HandlerString --zip-file fileb://target/HelloWorld-1.0.jar


